const mongoose = require('mongoose');

const studentSchema = new mongoose.Schema({
  "name": { type: String, required: false },
  "totalMarks": { type: Number, required: false },

  "roll": { type: String, required: false,unique:true },
  "studentClass": { type: String, required: false },

  "section": { type: String, required: false },
  "subject": { type: String, required: false },
  "terminal": { type: String, required: false },

  // Questions q1 to q25 with options from 'a' to 'j'
  "q1a": { type: Number, required: false },
  "q1b": { type: Number, required: false },
  "q1c": { type: Number, required: false },
  "q1d": { type: Number, required: false },
  "q1e": { type: Number, required: false },
  "q1f": { type: Number, required: false },
  "q1g": { type: Number, required: false },
  "q1h": { type: Number, required: false },
  "q1i": { type: Number, required: false },
  "q1j": { type: Number, required: false },
  "q1k": { type: Number, required: false },
  "q1l": { type: Number, required: false },
  "q1m": { type: Number, required: false },
  "q1n": { type: Number, required: false },
  "q1o": { type: Number, required: false },
  "q1p": { type: Number, required: false },
  "q1q": { type: Number, required: false },
  "q1r": { type: Number, required: false },
  "q1s": { type: Number, required: false },
  "q1t": { type: Number, required: false },
  "q1u": { type: Number, required: false },
  "q1v": { type: Number, required: false },
  "q1w": { type: Number, required: false },
  "q1x": { type: Number, required: false },
  "q1y": { type: Number, required: false },
  "q1z": { type: Number, required: false },
  "q1a_i": { type: Number, required: false },
  "q1a_ii": { type: Number, required: false },
  "q1a_iii": { type: Number, required: false },
  "q1a_iv": { type: Number, required: false },
  "q1a_v": { type: Number, required: false },
  "q1a_vi": { type: Number, required: false },
  "q1a_vii": { type: Number, required: false },
  "q1a_viii": { type: Number, required: false },
  "q1a_ix": { type: Number, required: false },
  "q1a_x": { type: Number, required: false },
  "q1a_xi": { type: Number, required: false },
  "q1a_xii": { type: Number, required: false },
  "q1a_xiii": { type: Number, required: false },
  "q1a_xiv": { type: Number, required: false },
  "q1a_xv": { type: Number, required: false },
  "q1b_i": { type: Number, required: false },
  "q1b_ii": { type: Number, required: false },
  "q1b_iii": { type: Number, required: false },
  "q1b_iv": { type: Number, required: false },
  "q1b_v": { type: Number, required: false },
  "q1b_vi": { type: Number, required: false },
  "q1b_vii": { type: Number, required: false },
  "q1b_viii": { type: Number, required: false },
  "q1b_ix": { type: Number, required: false },
  "q1b_x": { type: Number, required: false },
  "q1b_xi": { type: Number, required: false },
  "q1b_xii": { type: Number, required: false },
  "q1b_xiii": { type: Number, required: false },
  "q1b_xiv": { type: Number, required: false },
  "q1b_xv": { type: Number, required: false },
  "q1c_i": { type: Number, required: false },
  "q1c_ii": { type: Number, required: false },
  "q1c_iii": { type: Number, required: false },
  "q1c_iv": { type: Number, required: false },
  "q1c_v": { type: Number, required: false },
  "q1c_vi": { type: Number, required: false },
  "q1c_vii": { type: Number, required: false },
  "q1c_viii": { type: Number, required: false },
  "q1c_ix": { type: Number, required: false },
  "q1c_x": { type: Number, required: false },
  "q1c_xi": { type: Number, required: false },
  "q1c_xii": { type: Number, required: false },
  "q1c_xiii": { type: Number, required: false },
  "q1c_xiv": { type: Number, required: false },
  "q1c_xv": { type: Number, required: false },
  "q1d_i": { type: Number, required: false },
  "q1d_ii": { type: Number, required: false },
  "q1d_iii": { type: Number, required: false },
  "q1d_iv": { type: Number, required: false },
  "q1d_v": { type: Number, required: false },
  "q1d_vi": { type: Number, required: false },
  "q1d_vii": { type: Number, required: false },
  "q1d_viii": { type: Number, required: false },
  "q1d_ix": { type: Number, required: false },
  "q1d_x": { type: Number, required: false },
  "q1d_xi": { type: Number, required: false },
  "q1d_xii": { type: Number, required: false },
  "q1d_xiii": { type: Number, required: false },
  "q1d_xiv": { type: Number, required: false },
  "q1d_xv": { type: Number, required: false },
  "q1e_i": { type: Number, required: false },
  "q1e_ii": { type: Number, required: false },
  "q1e_iii": { type: Number, required: false },
  "q1e_iv": { type: Number, required: false },
  "q1e_v": { type: Number, required: false },
  "q1e_vi": { type: Number, required: false },
  "q1e_vii": { type: Number, required: false },
  "q1e_viii": { type: Number, required: false },
  "q1e_ix": { type: Number, required: false },
  "q1e_x": { type: Number, required: false },

  "q1e_xi": { type: Number, required: false },
  "q1e_xii": { type: Number, required: false },
  "q1e_xiii": { type: Number, required: false },
  "q1e_xiv": { type: Number, required: false },
  "q1e_xv": { type: Number, required: false },
  "q1f_i": { type: Number, required: false },
  "q1f_ii": { type: Number, required: false },
  "q1f_iii": { type: Number, required: false },
  "q1f_iv": { type: Number, required: false },
  "q1f_v": { type: Number, required: false },
  "q1f_vi": { type: Number, required: false },
  "q1f_vii": { type: Number, required: false },
  "q1f_viii": { type: Number, required: false },
  "q1f_ix": { type: Number, required: false },
  "q1f_x": { type: Number, required: false },
  "q1f_xi": { type: Number, required: false },
  "q1f_xii": { type: Number, required: false },
  "q1f_xiii": { type: Number, required: false },
  "q1f_xiv": { type: Number, required: false },
  "q1f_xv": { type: Number, required: false },  
  "q1g_i": { type: Number, required: false },
  "q1g_ii": { type: Number, required: false },
  "q1g_iii": { type: Number, required: false },
  "q1g_iv": { type: Number, required: false },
  "q1g_v": { type: Number, required: false },
  "q1g_vi": { type: Number, required: false },
  "q1g_vii": { type: Number, required: false },
  "q1g_viii": { type: Number, required: false },
  "q1g_ix": { type: Number, required: false },
  "q1g_x": { type: Number, required: false },
  "q1g_xi": { type: Number, required: false },
  "q1g_xii": { type: Number, required: false },
  "q1g_xiii": { type: Number, required: false },
  "q1g_xiv": { type: Number, required: false },
  "q1g_xv": { type: Number, required: false },
  "q1h_i": { type: Number, required: false },
  "q1h_ii": { type: Number, required: false },
  "q1h_iii": { type: Number, required: false },
  "q1h_iv": { type: Number, required: false },
  "q1h_v": { type: Number, required: false },
  "q1h_vi": { type: Number, required: false },
  "q1h_vii": { type: Number, required: false },
  "q1h_viii": { type: Number, required: false },
  



  "q2a": { type: Number, required: false },
  "q2b": { type: Number, required: false },
  "q2c": { type: Number, required: false },
  "q2d": { type: Number, required: false },
  "q2e": { type: Number, required: false },
  "q2f": { type: Number, required: false },
  "q2g": { type: Number, required: false },
  "q2h": { type: Number, required: false },
  "q2i": { type: Number, required: false },
  "q2j": { type: Number, required: false },
  
  //add upto z for all
  "q2k": { type: Number, required: false },
  "q2l": { type: Number, required: false },
  "q2m": { type: Number, required: false },
  "q2n": { type: Number, required: false },
  "q2o": { type: Number, required: false },
  "q2p": { type: Number, required: false },
  "q2q": { type: Number, required: false },
  "q2r": { type: Number, required: false },
  "q2s": { type: Number, required: false },
  "q2t": { type: Number, required: false },
  "q2u": { type: Number, required: false },
  "q2v": { type: Number, required: false },
  "q2w": { type: Number, required: false },
  "q2x": { type: Number, required: false },
  "q2y": { type: Number, required: false },
  "q2z": { type: Number, required: false },
  "q2a_i": { type: Number, required: false },
  "q2a_ii": { type: Number, required: false },
  "q2a_iii": { type: Number, required: false },
  "q2a_iv": { type: Number, required: false },
  "q2a_v": { type: Number, required: false },
  "q2a_vi": { type: Number, required: false },
  "q2a_vii": { type: Number, required: false },
  "q2a_viii": { type: Number, required: false },
  "q2a_ix": { type: Number, required: false },
  "q2a_x": { type: Number, required: false },
 "q2d_i": { type: Number, required: false },
  "q2d_ii": { type: Number, required: false },
  "q2d_iii": { type: Number, required: false },
  "q2d_iv": { type: Number, required: false },
  "q2d_v": { type: Number, required: false },
  "q2d_vi": { type: Number, required: false },
  "q2d_vii": { type: Number, required: false },
  "q2d_viii": { type: Number, required: false },
  "q2d_ix": { type: Number, required: false },
  "q2d_x": { type: Number, required: false },
 "q2f_i": { type: Number, required: false },
  "q2f_ii": { type: Number, required: false },
  "q2f_iii": { type: Number, required: false },
  "q2f_iv": { type: Number, required: false },
  "q2f_v": { type: Number, required: false },
  "q2f_vi": { type: Number, required: false },
  "q2f_vii": { type: Number, required: false },
  "q2f_viii": { type: Number, required: false },
  "q2f_ix": { type: Number, required: false },
  "q2f_x": { type: Number, required: false },

  "q3a": { type: Number, required: false },
  "q3b": { type: Number, required: false },
  "q3c": { type: Number, required: false },
  "q3d": { type: Number, required: false },
  "q3e": { type: Number, required: false },
  "q3f": { type: Number, required: false },
  "q3g": { type: Number, required: false },
  "q3h": { type: Number, required: false },
  "q3i": { type: Number, required: false },
  "q3j": { type: Number, required: false },
  "q3k": { type: Number, required: false },
  "q3l": { type: Number, required: false },
  "q3m": { type: Number, required: false },
  "q3n": { type: Number, required: false },

  //upto z
  "q3o": { type: Number, required: false },
  "q3p": { type: Number, required: false },
  "q3q": { type: Number, required: false },
  "q3r": { type: Number, required: false },
  "q3s": { type: Number, required: false },
  "q3t": { type: Number, required: false },
  "q3u": { type: Number, required: false },
  "q3v": { type: Number, required: false },
  "q3w": { type: Number, required: false },
  "q3x": { type: Number, required: false },
  "q3y": { type: Number, required: false },
  "q3z": { type: Number, required: false },
  
  // Sub-parts for q3a with decimal support
  "q3a_i": { type: Number, required: false },
  "q3a_ii": { type: Number, required: false },
  "q3a_iii": { type: Number, required: false },
  "q3a_iv": { type: Number, required: false },
  "q3a_v": { type: Number, required: false },
  "q3a_vi": { type: Number, required: false },
  "q3a_vii": { type: Number, required: false },
  "q3a_viii": { type: Number, required: false },
  "q3a_ix": { type: Number, required: false },
  "q3a_x": { type: Number, required: false },
  
  // Sub-parts for q3b with decimal support
  "q3b_i": { type: Number, required: false },
  "q3b_ii": { type: Number, required: false },
  "q3b_iii": { type: Number, required: false },
  "q3b_iv": { type: Number, required: false },
  "q3b_v": { type: Number, required: false },
  "q3b_vi": { type: Number, required: false },
  "q3b_vii": { type: Number, required: false },
  "q3b_viii": { type: Number, required: false },
  "q3b_ix": { type: Number, required: false },
  "q3b_x": { type: Number, required: false },
  
  // Sub-parts for q3c with decimal support
  "q3c_i": { type: Number, required: false },
  "q3c_ii": { type: Number, required: false },
  "q3c_iii": { type: Number, required: false },
  "q3c_iv": { type: Number, required: false },
  "q3c_v": { type: Number, required: false },
  "q3c_vi": { type: Number, required: false },
  "q3c_vii": { type: Number, required: false },
  "q3c_viii": { type: Number, required: false },
  "q3c_ix": { type: Number, required: false },
  "q3c_x": { type: Number, required: false },

   "q3d_i": { type: Number, required: false },
  "q3d_ii": { type: Number, required: false },
  "q3d_iii": { type: Number, required: false },
  "q3d_iv": { type: Number, required: false },
  "q3d_v": { type: Number, required: false },
  "q3d_vi": { type: Number, required: false },
  "q3d_vii": { type: Number, required: false },
  "q3d_viii": { type: Number, required: false },
  "q3d_ix": { type: Number, required: false },
  "q3d_x": { type: Number, required: false },

   "q3e_i": { type: Number, required: false },
  "q3e_ii": { type: Number, required: false },
  "q3e_iii": { type: Number, required: false },
  "q3e_iv": { type: Number, required: false },
  "q3e_v": { type: Number, required: false },
  "q3e_vi": { type: Number, required: false },
  "q3e_vii": { type: Number, required: false },
  "q3e_viii": { type: Number, required: false },
  "q3e_ix": { type: Number, required: false },
  "q3e_x": { type: Number, required: false },



  "q4a": { type: Number, required: false },
  "q4b": { type: Number, required: false },
  "q4c": { type: Number, required: false },
  "q4d": { type: Number, required: false },
  "q4e": { type: Number, required: false },
  "q4f": { type: Number, required: false },
  "q4g": { type: Number, required: false },
  
  // Sub-parts for q4a with decimal support
  "q4a_i": { type: Number, required: false },    // Can store 0_5, 1_0, 1_5 marks
  "q4a_ii": { type: Number, required: false },   // Can store 0_5, 1_0, 1_5 marks
  "q4a_iii": { type: Number, required: false },  // Can store 0_5, 1_0, 1_5 marks
  "q4a_iv": { type: Number, required: false },   // Can store 0_5, 1_0, 1_5 marks
  "q4a_v": { type: Number, required: false },    // Can store 0_5, 1_0, 1_5 marks
  
  // Sub-parts for q4b with decimal support
  "q4b_i": { type: Number, required: false },
  "q4b_ii": { type: Number, required: false },
  "q4b_iii": { type: Number, required: false },
  "q4b_iv": { type: Number, required: false },
  "q4b_v": { type: Number, required: false },
  "q4h": { type: Number, required: false },
  "q4i": { type: Number, required: false },
  "q4j": { type: Number, required: false },
  //add upto z at once
  "q4k": { type: Number, required: false },
  "q4l": { type: Number, required: false },
  "q4m": { type: Number, required: false },
  "q4n": { type: Number, required: false },
  "q4o": { type: Number, required: false },
  "q4p": { type: Number, required: false },
  "q4q": { type: Number, required: false },
  "q4r": { type: Number, required: false },
  "q4s": { type: Number, required: false },
  "q4t": { type: Number, required: false },
  "q4u": { type: Number, required: false },
  "q4v": { type: Number, required: false },
  "q4w": { type: Number, required: false },
  "q4x": { type: Number, required: false },
  "q4y": { type: Number, required: false },
  "q4z": { type: Number, required: false },
  

  "q5a": { type: Number, required: false },
  "q5b": { type: Number, required: false },
  "q5c": { type: Number, required: false },
  "q5d": { type: Number, required: false },
  "q5e": { type: Number, required: false },
  "q5f": { type: Number, required: false },
  "q5g": { type: Number, required: false },
  "q5h": { type: Number, required: false },
  "q5i": { type: Number, required: false },
  "q5j": { type: Number, required: false },
  "q5k": { type: Number, required: false },
  "q5l": { type: Number, required: false },
  "q5m": { type: Number, required: false },
  "q5n": { type: Number, required: false },
  "q5o": { type: Number, required: false },
  "q5p": { type: Number, required: false },
  "q5q": { type: Number, required: false },
  "q5r": { type: Number, required: false },
  "q5s": { type: Number, required: false },
  "q5t": { type: Number, required: false },
  "q5u": { type: Number, required: false },
  "q5v": { type: Number, required: false },
  "q5w": { type: Number, required: false },
  "q5x": { type: Number, required: false },
  "q5y": { type: Number, required: false },
  "q5z": { type: Number, required: false },


  "q6a": { type: Number, required: false },
  "q6b": { type: Number, required: false },
  "q6c": { type: Number, required: false },
  "q6d": { type: Number, required: false },
  "q6e": { type: Number, required: false },
  "q6f": { type: Number, required: false },
  "q6g": { type: Number, required: false },
  "q6h": { type: Number, required: false },
  "q6i": { type: Number, required: false },
  "q6j": { type: Number, required: false },
  "q6k": { type: Number, required: false },
  "q6l": { type: Number, required: false },
  "q6m": { type: Number, required: false },
  "q6n": { type: Number, required: false },
  "q6o": { type: Number, required: false },
  "q6p": { type: Number, required: false },
  "q6q": { type: Number, required: false },
  "q6r": { type: Number, required: false },
  "q6s": { type: Number, required: false },
  "q6t": { type: Number, required: false },
  "q6u": { type: Number, required: false },
  "q6v": { type: Number, required: false },
  "q6w": { type: Number, required: false },
  "q6x": { type: Number, required: false },
  "q6y": { type: Number, required: false },
  "q6z": { type: Number, required: false },


  "q7a": { type: Number, required: false },
  "q7b": { type: Number, required: false },
  "q7c": { type: Number, required: false },
  "q7d": { type: Number, required: false },
  "q7e": { type: Number, required: false },
  "q7f": { type: Number, required: false },
  "q7g": { type: Number, required: false },
  "q7h": { type: Number, required: false },
  "q7i": { type: Number, required: false },
  "q7j": { type: Number, required: false },
  "q7k": { type: Number, required: false },
  "q7l": { type: Number, required: false },
  "q7m": { type: Number, required: false },
  "q7n": { type: Number, required: false },
  "q7o": { type: Number, required: false },
  "q7p": { type: Number, required: false },
  "q7q": { type: Number, required: false },
  "q7r": { type: Number, required: false },
  "q7s": { type: Number, required: false },
  "q7t": { type: Number, required: false },
  "q7u": { type: Number, required: false },
  "q7v": { type: Number, required: false },
  "q7w": { type: Number, required: false },
  "q7x": { type: Number, required: false },
  "q7y": { type: Number, required: false },
  "q7z": { type: Number, required: false },

  "q8a": { type: Number, required: false },
  "q8b": { type: Number, required: false },
  "q8c": { type: Number, required: false },
  "q8d": { type: Number, required: false },
  "q8e": { type: Number, required: false },
  "q8f": { type: Number, required: false },
  "q8g": { type: Number, required: false },
  "q8h": { type: Number, required: false },
  "q8i": { type: Number, required: false },
  "q8j": { type: Number, required: false },
  "q8k": { type: Number, required: false },
  "q8l": { type: Number, required: false },
  "q8m": { type: Number, required: false },
  "q8n": { type: Number, required: false },
  "q8o": { type: Number, required: false },
  "q8p": { type: Number, required: false },
  "q8q": { type: Number, required: false },
  "q8r": { type: Number, required: false },
  "q8s": { type: Number, required: false },
  "q8t": { type: Number, required: false },
  "q8u": { type: Number, required: false },
  "q8v": { type: Number, required: false },
  "q8w": { type: Number, required: false },
  "q8x": { type: Number, required: false },
  "q8y": { type: Number, required: false },
  "q8z": { type: Number, required: false },


  "q9a": { type: Number, required: false },
  "q9b": { type: Number, required: false },
  "q9c": { type: Number, required: false },
  "q9d": { type: Number, required: false },
  "q9e": { type: Number, required: false },
  "q9f": { type: Number, required: false },
  "q9g": { type: Number, required: false },
  "q9h": { type: Number, required: false },
  "q9i": { type: Number, required: false },
  "q9j": { type: Number, required: false },
  "q9k": { type: Number, required: false },
  "q9l": { type: Number, required: false },
  "q9m": { type: Number, required: false },
  "q9n": { type: Number, required: false },
  "q9o": { type: Number, required: false },
  "q9p": { type: Number, required: false },
  "q9q": { type: Number, required: false },
  "q9r": { type: Number, required: false },
  "q9s": { type: Number, required: false },
  "q9t": { type: Number, required: false },
  "q9u": { type: Number, required: false },
  "q9v": { type: Number, required: false },
  "q9w": { type: Number, required: false },
  "q9x": { type: Number, required: false },
  "q9y": { type: Number, required: false },
  "q9z": { type: Number, required: false },


  "q10a": { type: Number, required: false },
  "q10b": { type: Number, required: false },
  "q10c": { type: Number, required: false },
  "q10d": { type: Number, required: false },
  "q10e": { type: Number, required: false },
  "q10f": { type: Number, required: false },
  "q10g": { type: Number, required: false },
  "q10h": { type: Number, required: false },
  "q10i": { type: Number, required: false },
  "q10j": { type: Number, required: false },
  "q10k": { type: Number, required: false },
  "q10l": { type: Number, required: false },
  "q10m": { type: Number, required: false },
  // add upto z at once

  "q10n": { type: Number, required: false },
  //add upto z at once
  "q10o": { type: Number, required: false },
  "q10p": { type: Number, required: false },
  "q10q": { type: Number, required: false },
  "q10r": { type: Number, required: false },
  "q10s": { type: Number, required: false },
  "q10t": { type: Number, required: false },
  "q10u": { type: Number, required: false },
  "q10v": { type: Number, required: false },
  "q10w": { type: Number, required: false },
  "q10x": { type: Number, required: false },
  "q10y": { type: Number, required: false },
  "q10z": { type: Number, required: false },

  // Repeat the same pattern for questions q11 to q25
  // For brevity, only q11 to q15 are listed here as an example

  "q11a": { type: Number, required: false },
  "q11b": { type: Number, required: false },
  "q11c": { type: Number, required: false },
  "q11d": { type: Number, required: false },
  "q11e": { type: Number, required: false },
  "q11f": { type: Number, required: false },
  "q11g": { type: Number, required: false },
  "q11h": { type: Number, required: false },
  "q11i": { type: Number, required: false },
  "q11j": { type: Number, required: false },

  //add upto z at once
  "q11k": { type: Number, required: false },
  "q11l": { type: Number, required: false },
  "q11m": { type: Number, required: false },
  "q11n": { type: Number, required: false },
  "q11o": { type: Number, required: false },
  "q11p": { type: Number, required: false },
  "q11q": { type: Number, required: false },
  "q11r": { type: Number, required: false },
  "q11s": { type: Number, required: false },
  "q11t": { type: Number, required: false },
  "q11u": { type: Number, required: false },
  "q11v": { type: Number, required: false },
  "q11w": { type: Number, required: false },
  "q11x": { type: Number, required: false },
  "q11y": { type: Number, required: false },
  "q11z": { type: Number, required: false },

  "q12a": { type: Number, required: false },
  "q12b": { type: Number, required: false },
  "q12c": { type: Number, required: false },
  "q12d": { type: Number, required: false },
  "q12e": { type: Number, required: false },
  "q12f": { type: Number, required: false },
  "q12g": { type: Number, required: false },
  "q12h": { type: Number, required: false },
  "q12i": { type: Number, required: false },
  "q12j": { type: Number, required: false },
  "q12k": { type: Number, required: false },
  "q12l": { type: Number, required: false },
  "q12m": { type: Number, required: false },
  "q12n": { type: Number, required: false },
  //add upto z at once
  "q12o": { type: Number, required: false },
  "q12p": { type: Number, required: false },
  "q12q": { type: Number, required: false },
  "q12r": { type: Number, required: false },
  "q12s": { type: Number, required: false },
  "q12t": { type: Number, required: false },
  "q12u": { type: Number, required: false },
  "q12v": { type: Number, required: false },
  "q12w": { type: Number, required: false },
  "q12x": { type: Number, required: false },
  "q12y": { type: Number, required: false },
  "q12z": { type: Number, required: false },

  "q13a": { type: Number, required: false },
  "q13b": { type: Number, required: false },
  "q13c": { type: Number, required: false },
  "q13d": { type: Number, required: false },
  "q13e": { type: Number, required: false },
  "q13f": { type: Number, required: false },
  "q13g": { type: Number, required: false },
  "q13h": { type: Number, required: false },
  "q13i": { type: Number, required: false },
  "q13j": { type: Number, required: false },
  "q13k": { type: Number, required: false },
  "q13l": { type: Number, required: false },
  "q13m": { type: Number, required: false },
  "q13n": { type: Number, required: false },
  "q13o": { type: Number, required: false },
  "q13p": { type: Number, required: false },
  "q13q": { type: Number, required: false },
  "q13r": { type: Number, required: false },
  "q13s": { type: Number, required: false },
  "q13t": { type: Number, required: false },
  "q13u": { type: Number, required: false },
  "q13v": { type: Number, required: false },
  "q13w": { type: Number, required: false },
  "q13x": { type: Number, required: false },
  "q13y": { type: Number, required: false },
  "q13z": { type: Number, required: false },


  "q14a": { type: Number, required: false },
  "q14b": { type: Number, required: false },
  "q14c": { type: Number, required: false },
  "q14d": { type: Number, required: false },
  "q14e": { type: Number, required: false },
  "q14f": { type: Number, required: false },
  "q14g": { type: Number, required: false },
  "q14h": { type: Number, required: false },
  "q14i": { type: Number, required: false },
  "q14j": { type: Number, required: false },
  // add "q14k" to "q14z" at once
  "q14k": { type: Number, required: false },
  "q14l": { type: Number, required: false },
  "q14m": { type: Number, required: false },
  "q14n": { type: Number, required: false },
  "q14o": { type: Number, required: false },
  "q14p": { type: Number, required: false },
  "q14q": { type: Number, required: false },
  "q14r": { type: Number, required: false },
  "q14s": { type: Number, required: false },
  "q14t": { type: Number, required: false },
  "q14u": { type: Number, required: false },  
  "q14v": { type: Number, required: false },
  "q14w": { type: Number, required: false },
  

  "q15a": { type: Number, required: false },
  "q15b": { type: Number, required: false },
  "q15c": { type: Number, required: false },
  "q15d": { type: Number, required: false },
  "q15e": { type: Number, required: false },
  "q15f": { type: Number, required: false },
  "q15g": { type: Number, required: false },
  "q15h": { type: Number, required: false },
  "q15i": { type: Number, required: false },
  "q15j": { type: Number, required: false },

  "q16a": { type: Number, required: false },
  "q16b": { type: Number, required: false },
  "q16c": { type: Number, required: false },
  "q16d": { type: Number, required: false },
  "q16e": { type: Number, required: false },
  "q16f": { type: Number, required: false },
  "q16g": { type: Number, required: false },
  "q16h": { type: Number, required: false },
  "q16i": { type: Number, required: false },
  "q16j": { type: Number, required: false },

  "q17a": { type: Number, required: false },
  "q17b": { type: Number, required: false },
  "q17c": { type: Number, required: false },
  "q17d": { type: Number, required: false },
  "q17e": { type: Number, required: false },
  "q17f": { type: Number, required: false },
  "q17g": { type: Number, required: false },
  "q17h": { type: Number, required: false },
  "q17i": { type: Number, required: false },
  "q17j": { type: Number, required: false },

  "q18a": { type: Number, required: false },
  "q18b": { type: Number, required: false },
  "q18c": { type: Number, required: false },
  "q18d": { type: Number, required: false },
  "q18e": { type: Number, required: false },
  "q18f": { type: Number, required: false },
  "q18g": { type: Number, required: false },
  "q18h": { type: Number, required: false },
  "q18i": { type: Number, required: false },
  "q18j": { type: Number, required: false },

  "q19a": { type: Number, required: false },
  "q19b": { type: Number, required: false },
  "q19c": { type: Number, required: false },
  "q19d": { type: Number, required: false },
  "q19e": { type: Number, required: false },
  "q19f": { type: Number, required: false },
  "q19g": { type: Number, required: false },
  "q19h": { type: Number, required: false },
  "q19i": { type: Number, required: false },
  "q19j": { type: Number, required: false },

  "q20a": { type: Number, required: false },
  "q20b": { type: Number, required: false },
  "q20c": { type: Number, required: false },
  "q20d": { type: Number, required: false },
  "q20e": { type: Number, required: false },
  "q20f": { type: Number, required: false },
  "q20g": { type: Number, required: false },
  "q20h": { type: Number, required: false },
  "q20i": { type: Number, required: false },
  "q20j": { type: Number, required: false },

  "q21a": { type: Number, required: false },
  "q21b": { type: Number, required: false },
  "q21c": { type: Number, required: false },
  "q21d": { type: Number, required: false },
  "q21e": { type: Number, required: false },
  "q21f": { type: Number, required: false },
  "q21g": { type: Number, required: false },
  "q21h": { type: Number, required: false },
  "q21i": { type: Number, required: false },
  "q21j": { type: Number, required: false },

  "q22a": { type: Number, required: false },
  "q22b": { type: Number, required: false },
  "q22c": { type: Number, required: false },
  "q22d": { type: Number, required: false },
  "q22e": { type: Number, required: false },
  "q22f": { type: Number, required: false },
  "q22g": { type: Number, required: false },
  "q22h": { type: Number, required: false },
  "q22i": { type: Number, required: false },
  "q22j": { type: Number, required: false },

  "q23a": { type: Number, required: false },
  "q23b": { type: Number, required: false },
  "q23c": { type: Number, required: false },
  "q23d": { type: Number, required: false },
  "q23e": { type: Number, required: false },
  "q23f": { type: Number, required: false },
  "q23g": { type: Number, required: false },
  "q23h": { type: Number, required: false },
  "q23i": { type: Number, required: false },
  "q23j": { type: Number, required: false },

  "q24a": { type: Number, required: false },
  "q24b": { type: Number, required: false },
  "q24c": { type: Number, required: false },
  "q24d": { type: Number, required: false },
  "q24e": { type: Number, required: false },
  "q24f": { type: Number, required: false },
  "q24g": { type: Number, required: false },
  "q24h": { type: Number, required: false },
  "q24i": { type: Number, required: false },
  "q24j": { type: Number, required: false },

  "q25a": { type: Number, required: false },
  "q25b": { type: Number, required: false },
  "q25c": { type: Number, required: false },
  "q25d": { type: Number, required: false },
  "q25e": { type: Number, required: false },
  "q25f": { type: Number, required: false },
  "q25g": { type: Number, required: false },
  "q25h": { type: Number, required: false },
  "q25i": { type: Number, required: false },
  "q25j": { type: Number, required: false }

  

});

module.exports = {studentSchema};
